name: real-test
route: /test
method: POST
description: Rule-based analyzed workflow
workflow_file: test.json
timeout: 120
backend_servers:
- server-0ef300
- server-06ef32
- server-2db788
inputs:
- name: width
  type: integer
  required: false
  default: 1024
  description: EmptyLatentImage 节点 51 的 width
  inject_to:
    node_id: '51'
    field: width
- name: height
  type: integer
  required: false
  default: 1824
  description: EmptyLatentImage 节点 51 的 height
  inject_to:
    node_id: '51'
    field: height
- name: batch_size
  type: integer
  required: false
  default: 1
  description: EmptyLatentImage 节点 51 的 batch_size
  inject_to:
    node_id: '51'
    field: batch_size
- name: text_71
  type: string
  required: false
  description: CLIPTextEncode 节点 71 的文本输入
  inject_to:
    node_id: '71'
    field: text
- name: text_72
  type: string
  required: false
  description: CLIPTextEncode 节点 72 的文本输入
  inject_to:
    node_id: '72'
    field: text
- name: seed
  type: integer
  required: false
  default: -1
  description: KSampler 节点 74 的 seed
  inject_to:
    node_id: '74'
    field: seed
- name: steps
  type: integer
  required: false
  default: 30
  description: KSampler 节点 74 的 steps
  inject_to:
    node_id: '74'
    field: steps
- name: cfg
  type: integer
  required: false
  default: 2.5
  description: KSampler 节点 74 的 cfg
  inject_to:
    node_id: '74'
    field: cfg
output_node_id: '342'
