name: Z-IMAGE
route: /z_image
method: POST
description: Z-IMAGE
workflow_file: image_z_image01.json
timeout: 120
backend_servers:
- server-0ef300
- server-c06639
- server-06ef32
- server-838e44
- server-2db788
- server-27283f
- server-319f68
- server-c7cfd6
inputs:
- name: prompt
  type: string
  required: false
  description: CLIPTextEncode 节点 67 的文本输入
  inject_to:
    node_id: '67'
    field: text
- name: seed
  type: integer
  required: false
  default: -1
  description: KSampler 节点 69 的 seed
  inject_to:
    node_id: '69'
    field: seed
- name: steps
  type: integer
  required: false
  default: 30
  description: KSampler 节点 69 的 steps
  inject_to:
    node_id: '69'
    field: steps
- name: cfg
  type: integer
  required: false
  default: 4
  description: KSampler 节点 69 的 cfg
  inject_to:
    node_id: '69'
    field: cfg
output_node_id: '9'
